### PR TITLE
Create Veterans Affairs SSVF Survey 2016-17 data

### PR DESCRIPTION
**Pull request by Lynn99kek**

### CODE REVIEW

**Comment by ben-domingue** [comment]
@Lynn99kek checking that the code here is up-to-date?

**Comment by Lynn99kek** [comment]
I think they are up-to-date now!
Sorry I am just trying with the github.

**Comment by ben-domingue** [comment]
oh, gotcha. so we are all good?

**Comment by Lynn99kek** [comment]
I think yes!

**Pull request merged**
